### ISSUE TITLE
How does this plugin benefit me?

### ISSUE THREAD

**Issue by Zekken01** [DeathStrikeV/EvenBetterDiscord#1]

**Comment by Skykurohi** [comment]
It's mainly useful for loading FFZ emotes from an alternate repository (it's hardcoded at the moment, but you can replace it yourself). By default it's configured to my repository since I'm the only maintainer of that file at the moment, so basically as soon as I do an emotes update, you'll get it immediately without having to wait for it to get pulled and approved into the main BetterDiscord repository.

**Comment by Zekken01** [comment]
oh so it like an always up to date repository? That's nice.
